
services:
  # 백엔드 설정
  backend:
    build: ./backend
    ports:
      - "8080:8080"

  # 프론트엔드 설정
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  # Nginx (입구) 설정
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
